feat: install flag added and bump up version
Signed-off-by: Savitoj <savitojs@gmail.com>

diff --git a/gurbani-fetch-n-play b/gurbani-fetch-n-play
--- a/gurbani-fetch-n-play
+++ b/gurbani-fetch-n-play
@@ -1,12 +1,45 @@
 #!/bin/bash
 
-VERSION="v0.2"
+# Script Name: gurbani-fetch-n-play
+# Description:
+#   Fetches and plays live Gurbani channels from Sikhnet.com
+#   This script is humbly devoted to the Almighty, with gratitude and reverence
+# Author: Savitoj Singh
+# Date: 2024-09-06
+# License: MIT License
 
-GREEN='\033[0;32m'
+VERSION="v0.4"
+
+# Colors Palette for reference
+BLACK='\033[0;30m'
 RED='\033[0;31m'
+GREEN='\033[0;32m'
 YELLOW='\033[0;33m'
 BLUE='\033[0;34m'
-NC='\033[0m' # No Color
+PURPLE='\033[0;35m'
+CYAN='\033[0;36m'
+WHITE='\033[0;37m'
+
+BRIGHT_BLACK='\033[0;90m'
+BRIGHT_RED='\033[0;91m'
+BRIGHT_GREEN='\033[0;92m'
+BRIGHT_YELLOW='\033[0;93m'
+BRIGHT_BLUE='\033[0;94m'
+BRIGHT_PURPLE='\033[0;95m'
+BRIGHT_CYAN='\033[0;96m'
+BRIGHT_WHITE='\033[0;97m'
+
+BG_BLACK='\033[40m'
+BG_RED='\033[41m'
+BG_GREEN='\033[42m'
+BG_YELLOW='\033[43m'
+BG_BLUE='\033[44m'
+BG_PURPLE='\033[45m'
+BG_CYAN='\033[46m'
+BG_WHITE='\033[47m'
+
+# Reset/No Color
+NC='\033[0m'
 
 SCRIPT_URL="https://raw.githubusercontent.com/savitojs/gurbani-fetch-n-play/main/gurbani-fetch-n-play"
 
@@ -14,13 +47,14 @@ CHECK_SYMBOL='\u2713'
 X_SYMBOL='\u2A2F'
 
 function display_help() {
-    echo -e "${YELLOW}Usage:${NC} ./fetch-n-play [options]"
+    echo -e "${YELLOW}Usage:${NC} $(basename $0) [options]"
     echo -e "${BLUE}Options:${NC}"
     echo -e "  ${GREEN}-h, --help${NC}      Show this help message and exit"
     echo -e "  ${GREEN}-s, --stop${NC}      Stop the current VLC playback"
     echo -e "  ${GREEN}-t, --status${NC}    Show online status of available channels"
+    echo -e "  ${GREEN}-i, --install${NC}   Install the script to writeable PATH"
     echo -e "  ${GREEN}-u, --update${NC}    Update the script to the latest version"
-    echo -e "  ${GREEN}-v, --version${NC}    Show the script version and exit"
+    echo -e "  ${GREEN}-v, --version${NC}   Show the script version and exit"
     echo -e "${YELLOW}Description:${NC}"
     echo -e "  This script fetches live Gurbani channels from Sikhnet.com and allows you to play them using VLC."
     echo -e "  You can run the script to select and play a channel, show their online status, or use the --stop option to stop playback."
@@ -33,19 +67,52 @@ function show_version() {
     exit 0
 }
 
-function update_script() {
-    echo -e "${YELLOW}IMPORTANT:${NC} This will replace the current script file!"
-    echo -e "If you continue, your current version of the script will be overwritten."
-    echo -en "Press ${GREEN}Enter${NC} to continue or ${RED}Ctrl+C${NC} to cancel"
-    
-    read -p ": "
+function install_script() {
+    local script_name="gurbani-fetch-n-play"
+    local available_dirs=()
 
+    IFS=':' read -r -a path_dirs <<< "$PATH"
+    echo -e "${YELLOW}Checking for writable directories in your PATH...${NC}"
+
+    for dir in "${path_dirs[@]}"; do
+        if [ -d "$dir" ] && [ -w "$dir" ]; then
+            available_dirs+=("$dir")
+        fi
+    done
+
+    if [ ${#available_dirs[@]} -eq 0 ]; then
+        echo -e "${RED}No writable directories found in your PATH.${NC}"
+        echo -e "${YELLOW}Please add a writable directory to your PATH or manually install the script.${NC}"
+        exit 1
+    fi
+
+    echo -e "${GREEN}The following directories in your PATH are writable:${NC}"
+    select target_dir in "${available_dirs[@]}"; do
+        if [ -n "$target_dir" ]; then
+            echo -e "${YELLOW}Installing the script to $target_dir...${NC}"
+            install -m 0755 "./$script_name" "$target_dir"
+
+            if [ $? -eq 0 ]; then
+                echo -e "${GREEN}Script installed successfully to $target_dir.${NC}"
+                exit 0
+            else
+                echo -e "${RED}Failed to install the script. Please try again.${NC}"
+                exit 1
+            fi
+            break
+        else
+            echo -e "${RED}Invalid selection. Please choose a valid directory.${NC}"
+        fi
+    done
+}
+
+function update_script() {
     echo -e "${YELLOW}Checking for updates...${NC}"
 
     UPSTREAM_VERSION=$(curl -s https://raw.githubusercontent.com/savitojs/gurbani-fetch-n-play/main/gurbani-fetch-n-play | grep '^VERSION=' | cut -d '"' -f 2)
 
     if [ "$UPSTREAM_VERSION" == "$VERSION" ]; then
-        echo -e "${GREEN}You are already using the latest version ($VERSION). No update required.${NC}"
+        echo -e "${GREEN}You are already using the latest version ($VERSION). ✨ No update required.${NC}"
         exit 0
     fi
 
@@ -53,6 +120,16 @@ function update_script() {
         echo -e "${RED}Error: Cannot write to the $(dirname $0). Try running with sudo${NC}"
         exit 1
     fi
+
+    echo ""
+		echo -e "${PURPLE}!!!!!! Update Available !!!!!!${NC}"
+    echo -e "Installed version: ${RED}${VERSION}${NC}\nUpstream version:  ${GREEN}${UPSTREAM_VERSION}${NC}"
+    echo ""
+    echo -e "${YELLOW}IMPORTANT:${NC} This will replace the installed script `which $0`"
+    echo -e "If you continue, your current version of the script will be overwritten."
+    echo -en "Press ${GREEN}Enter${NC} to continue or ${RED}Ctrl+C${NC} to cancel"
+
+    read -p ": "
 
     curl -o "$0" -s "$SCRIPT_URL"
     
@@ -64,7 +141,6 @@ function update_script() {
     fi
     exit 0
 }
-
 
 function stop_playback() {
     echo -e "${RED}Stopping the stream in the background...${NC}"
@@ -187,6 +263,9 @@ while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
     -t | --status )
       show_status
       ;;
+    -i | --install )
+      install_script
+      ;;
     -u | --update )
       update_script
       ;;
@@ -263,7 +342,7 @@ while true; do
               stop_playback && exit 0
               ;;
           "💤  Play in background")
-              echo -e "${BLUE}Quitting the script.${NC} \n${GREEN}You can stop the background playback running: $0 --stop"
+              echo -e "${BLUE}Quitting the script.${NC} \n${GREEN}You can stop the background playback running: $(basename $0) --stop"
               exit
               ;;
           "🔄  Switch radio channel")
